#ifdef EN
#define m_main "1.Start fishing, 2.Enter shop, 3.Setting, 4.Lucky Draw, 5.Challenging, 6.Exit."
#define m_did "Challenge Completed"
#define chp_suc "Load succeeded"
#define chp_err "Checkpoint is damaged"
#define chp_nouser "Incorrect username or password"
#define chp_login "Login"
#define chp_regi "Sign up"
#define chp_un "Username: "
#define chp_invalid "Invalid Username"
#define chp_pwd "Password: "
#define chp_repwd "Confirm password: "
#define chp_pwdng "Passwords do not match"
#define chp_yesuser "User already exists"
#define chp_regigood "Successfully registered"
#define chp_main "1.Login, 2.Sign up, 3.Exit"
#define fi_wea {"Rain", "Snow", "Sunny     ", "Overcast  ", "Cloudy    ", "Fog       "}
#define fi_big {"", "   Light ", "Moderate ", "   Heavy "}
#define fi_type {"Rotten ", "Common ", "Amethyst ", "Lapis Lazuli ", "Gold ", "Emerald ", "Diamond "}
#define fi_got "You caught a(n)"
#define fi_bf "big"
#define fi_eaten "fish\033[m.You ate it because you are hungry"
#define fi_price "fush\033[m, worth$"
#define fi_inaqua "Put into the aquarium"
#define fi_shi "Screen height must be at least 18 rows"
#define fi_sw "Screen width must be at least 44 columns"
#define fi_sn "Current size: "
#define fi_hi " rows"
#define fi_w " columns"
#define fi_allfi "Total fish caught: "
#define fi_nowwea " Current weather: "
#define fi_getgan "Rod Shop"
#define fi_nowgan "Current rod: "
#define fi_gan "rod"
#define fi_no "None"
#define fi_exit "7.Exit"
#define fi_aq "Aquarium"
#define fi_aqtip "Tip: You can only earn aquarium profits while in the aquarium"
#define fi_aexit "1.Exit"
#define fi_f "fish: "
#define fi_azhi "fish(es)\033[m"
#define fi_aget "You’ve gained $"
#define fi_aget2 " in profit"
#define fi_mfr "Raw Fish"
#define fi_mfn "Current amount: "
#define fi_azhi2 " fish(es)"
#define fi_chi "    Fish pond: "
#define fi_raw "    Raw fish: "
#define fi_roast "    Roasted Fish: "
#define fi_no2 "    None\033[m"
#define fi_ro "Prepare roasted fish"
#define fi_f2 "fish"
#define fi_romain "Press A to decrease, D to increase, Enter to make, Backspace to exit"
#define fi_rom2 "Making roasted fish: "
#define fi_rob "Roasting..."
#define fi_rod " Done"
#define fi_rodone "Roasting finished"
#define fi_em "Eat raw fish"
#define fi_nowhun "Current hunger: "
#define fi_eraw "raw fish"
#define fi_ezhi " pcs +"
#define fi_eroast "Eat roasted fish"
#define fi_erof "roasted fish"
#define fi_nrm "1.Make food, 2.Eat raw fish, 3.Exit"
#define fi_rm "1.Make food, 2.Roast food, 3.Eat raw fish, 4.Eat roasted fish, 5.Exit"
#define fi_sum1 "Pollution is full.Most fish died due to illness.\033[m"
#define fi_sum2 "1.Clean the fishpond"
#define fi_sum3 "1.Start fishing, 2.Clean pond, 3.Buy fishing rod, 4.View aquarium, 5.Make food, 6.Sell all, 7.Sell all and exit"
#define fi_sum4 "Current rod: "
#define fi_sum5 "Current pollution: "
#define fi_scl "    Freshness:"
#define fi_ncl "No cleaning needed"
#define fi_cl "1.Clean, 2.Exit"
#define fi_iscl "Current pollution: "
#define fi_clbcnt "Cleaning supplies: "
#define fi_clm1 "1.Buy cleaning supplies and clean, 2.Exit"
#define fi_cldt "Current pollution: "
#define fi_clji "Cleaning supplies: "
#define fi_clbuy "    Cost: $20, Your money: $"
#define fi_mnng "Not enough money"
#define fi_clok "Cleaning completed"
#define fi_nwt "Please buy an aquarium before viewing"
#define press_enter_continue "(Press Enter to continue)"
#define fun_choose {"Please choose a starting skill", "1.Delicious Bait, 2.Rare Treasures, 3.Secure Safety Rope, 4.Powerful Cleaner, 5.Popeye the Sailor, 6.Long Line for Big Fish, 7.Poor Family", "Delicious Bait:", "    Hooking speed becomes 1.5× of the original", "Rare Treasures:", "    Fish prices become 2× of the original", "Secure Safety Rope:", "    Slip-off chance changes from 50% to 10%", "Powerful Cleaner:", "    Start with 1 cleaner, and cleaner effectiveness is doubled", "Popeye the Sailor:", "    Casting speed changes from 1× to 2×", "Long Line for Big Fish:", "    Big fish chance changes from 20% to 40%", "Poor Family:", "    None"}
#define fi_egg "Egg Fish\033[m, worth $"
#define st_speed {"Slow", "Normal", "Fast"}
#define st_speeds "1.Slow, 2.Normal, 3.Fast"
#define st_m "1.Edit output speed, 2.Exit"
#define st_m2 "Current output speed: "
#define pk_in "Do you want to enter parkour mode?"
#define pk_tip1 "Use 'w' or space to jump, press 'r' to respawn, press backspace to exit"
#define pk_ok "Challenge completed, you earned $500"
#define pk_die "You died"
#define pk_rb "Do you want to respawn?"
#define pk_tip2 "Use 'wasd' to swim, press 'r' to respawn, press backspace to exit"
#else
#define m_main "1.开始钓鱼, 2.进入商店, 3.设置, 4.抽奖, 5.挑战, 6.退出, 其他输入无效。"
#define m_did "已完成挑战"
#define chp_suc "读取成功"
#define chp_err "存档损坏"
#define chp_nouser "用户名或密码错误"
#define chp_login "登录"
#define chp_regi "注册"
#define chp_un "用户名: "
#define chp_invalid "用户名不合法"
#define chp_pwd "密码: "
#define chp_repwd "请确认密码: "
#define chp_pwdng "两次密码不一致"
#define chp_yesuser "用户已存在"
#define chp_regigood "注册成功"
#define chp_main "1.登录, 2.注册, 3.退出"
#define fi_wea {"雨    ", "雪    ", "晴      ", "阴      ", "多云    ", "雾      "}
#define fi_big {"", "小", "中", "大"}
#define fi_type {"腐烂的", "普通的", "紫水晶", "青金石", "金", "绿宝石", "钻石"}
#define fi_got "你钓到了一条"
#define fi_bf "大"
#define fi_eaten "鱼\033[m, 因饥饿已食用"
#define fi_price "鱼\033[m, 价值$"
#define fi_inaqua "是否放入水族馆"
#define fi_shi "屏幕高度需至少为18行"
#define fi_sw "屏幕宽度需至少为44行"
#define fi_sn "当前为 "
#define fi_hi " 行"
#define fi_w " 列"
#define fi_allfi "累计钓鱼数量: "
#define fi_nowwea " 当前天气: "
#define fi_getgan "鱼竿兑换"
#define fi_nowgan "当前鱼竿: "
#define fi_gan "鱼竿"
#define fi_no "暂无"
#define fi_exit "7.退出"
#define fi_aq "水族馆"
#define fi_aqtip "提示: 只有在水族馆里才能获得水族馆的收益"
#define fi_aexit "1.退出"
#define fi_f "鱼: "
#define fi_azhi "只\033[m"
#define fi_aget "你共获得 "
#define fi_aget2 "$ 的收益"
#define fi_mfr "生鱼肉"
#define fi_mfn "当前数量: "
#define fi_azhi2 " 只"
#define fi_chi "    鱼池: "
#define fi_raw "    生鱼: "
#define fi_roast "    烤鱼: "
#define fi_no2 "    暂无\033[m"
#define fi_ro "制作烤鱼"
#define fi_f2 "鱼"
#define fi_romain "按 a 减少, d 增加, 按 enter 制作, 按 backspace 退出"
#define fi_rom2 "制作熟鱼肉: "
#define fi_rob "烤制中"
#define fi_rod " 完成"
#define fi_rodone "烤制完成"
#define fi_em "食用生鱼肉"
#define fi_nowhun "当前饱食度: "
#define fi_eraw "生鱼"
#define fi_ezhi " 只 +"
#define fi_eroast "食用熟鱼肉"
#define fi_erof "熟鱼"
#define fi_nrm "1.制作食物, 2.食用生鱼肉, 3.退出"
#define fi_rm "1.制作食物, 2.烤制食物, 3.食用生鱼肉, 4.食用熟鱼肉, 5.退出"
#define fi_sum1 "当前污染等级已满, 大部分鱼因病死亡\033[m"
#define fi_sum2 "1.清理鱼池"
#define fi_sum3 "1.开始钓鱼, 2.清理鱼池, 3.购买钓竿, 4.查看水族馆, 5.制作食物, 6.全部卖出, 7.全部卖出并退出"
#define fi_sum4 "当前鱼竿: "
#define fi_sum5 "当前污染等级: "
#define fi_scl "    新鲜度:"
#define fi_ncl "无需清理"
#define fi_cl "1.清理, 2.退出"
#define fi_iscl "当前污染等级: "
#define fi_clbcnt "当前清洁剂个数: "
#define fi_clm1 "1.购买清洁剂并清理, 2.退出"
#define fi_cldt "当前污染等级: "
#define fi_clji "清洁剂: "
#define fi_clbuy "    购买花费: $20, 当前金币数量: $"
#define fi_mnng "金钱不够"
#define fi_clok "清理完成"
#define fi_nwt "请在购买水族馆后在来查看"
#define press_enter_continue "(按enter继续)"
#define fun_choose {"请选择开局技能", "1.美味诱饵, 2.稀世珍宝, 3.牢靠安全绳, 4.强效清洁剂, 5.大力水手, 6.放长线钓大鱼, 7.孤苦人家", "美味诱饵:", "    上钩速度变为原先的1.5倍", "稀世珍宝:", "    鱼的价格变为原先的2倍", "牢靠安全绳:", "    脱钩概率由50%变为10%", "强效清洁剂:", "    初始获得1个清洁剂, 并且清洁剂效果翻倍", "大力水手:", "    甩杆倍速由1倍变为2倍", "放长线钓大鱼:", "    大鱼概率由20%变为40%", "孤苦人家:", "    无"}
#define fi_egg "鸡蛋鱼\033[m, 价值$"
#define st_speed {"慢速", "普通", "急速"}
#define st_speeds "1.慢速, 2.普通, 3.急速"
#define st_m "1.更改输出速度, 2.退出"
#define st_m2 "当前输出速度: "

#define pk_in "是否进入跑酷"
#define pk_tip1 "使用w或空格进行跳跃, 按r重生, 按backspace退出"
#define pk_ok "完成挑战, 获得 $500"
#define pk_die "你死了"
#define pk_rb "是否重生"
#define pk_tip2 "使用wasd进行游泳, 按r重生, 按backspace退出"
#endif